language: python

python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"

env:
  - DJANGO=https://www.djangoproject.com/download/1.7a2/tarball/
  - DJANGO=1.6.2
  - DJANGO=1.5.5
  - DJANGO=1.4.10

install:
  - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt
  - pip install -q -e .
  - pip install pep8
  - pip install https://github.com/un33k/pyflakes/tarball/master

before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E128 ."
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pyflakes -x W ipware; fi

matrix:
  exclude:
   - python: "3.3"
     env: DJANGO=1.4.10
   - python: "3.2"
     env: DJANGO=1.4.10

script: python manage.py test
